### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by scottgigante-immunai** [csbl-usp/CEMiTool#94] opened 2022-09-26 17:38 UTC
I get this error after installing from bioconda:

```
> library(CEMiTool)
Error: package or namespace load failed for ‘CEMiTool’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘quantreg’ 5.86 is being loaded, but >= 5.93 is required
```
If I upgrade quantreg:
```
> library(CEMiTool)

Warning message:
In .recacheSubclasses(def@className, def, env) :
  undefined subclass "numericVector" of class "Mnumeric"; definition not updated
```

Running R 4.0 on Debian 10.
```
R version 4.0.5 (2021-03-31) -- "Shake and Throw"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)
```

**Comment by pedrostrusso** [comment] 2022-09-26 19:10
Hi @scottgigante-immunai 

This isn't really a problem with the CEMiTool package. I googled your error message for a bit and it seems that that error shows up because of some problem with the Matrix (or maybe MatrixModels) package. Unfortunately, I'm not familiar with bioconda so I can't really help you there but maybe try updating those packages? They aren't really even direct dependencies from CEMiTool, but rather some other underlying packages (a.k.a. dependencies of dependencies). I'm closing the issue since I can't reproduce the error. 

Here are a few of the links I checked, maybe they can help
https://discourse.mc-stan.org/t/weird-message-recachesubclasses-mnumeric/22362
https://github.com/quanteda/quanteda/issues/2116
https://www.mail-archive.com/r-devel@r-project.org/msg43553.html

**Closed by pedrostrusso** 2022-09-26 19:10 UTC
