### ISSUE TITLE
CEMiTool version from repository breaks legacy code based on map loop

### ISSUE THREAD

**Issue by diolima** [csbl-usp/CEMiTool#25] opened 2018-04-03 05:19 UTC
Version from master returns error when function is called inside nested loop. Code was working with Bioconductor version.
I believe that error is caused by opening a graphical device. 
Error message:
<simpleError in (function (display = "", width, height, pointsize, gamma, bg,     canvas, fonts, family, xpos, ypos, title, type, antialias) {    if (display != "XImage") {        check <- Sys.getenv("_R_CHECK_SCREEN_DEVICE_", "")        msg <- "screen devices should not be used in examples etc"        if (identical(check, "stop"))             stop(msg, domain = NA)        else if (identical(check, "warn"))             warning(msg, immediate. = TRUE, noBreaks. = TRUE,                 domain = NA)    }    if (display == "" && .Platform$GUI == "AQUA" && is.na(Sys.getenv("DISPLAY",         NA)))         Sys.setenv(DISPLAY = ":0")    new <- list()    if (!missing(display))         new$display <- display    if (!missing(width))         new$width <- width    if (!missing(height))         new$height <- height    if (!missing(gamma))         new$gamma <- gamma    if (!missing(pointsize))         new$pointsize <- pointsize    if (!missing(bg))         new$bg <- bg    if (!missing(canvas))         new$canvas <- canvas    if (!missing(xpos))         new$xpos <- xpos    if (!missing(ypos))         new$ypos <- ypos    if (!missing(title))         new$title <- title    if (!checkIntFormat(new$title))         stop("invalid 'title'")    if (!missing(type)) {        new$type <- match.arg(type, c("Xlib", "cairo", "nbcairo",             "dbcairo"))        if (!capabilities("cairo") && type != "Xlib")             warning("cairo-based types are not supported on this build - using \"Xlib\"")    }    if (!missing(family))         new$family <- family    if (!missing(fonts))         new$fonts <- fonts    if (!missing(antialias) && type != "Xlib")         new$antialias <- match.arg(antialias, aa.cairo)    d <- check.options(new, name.opt = ".X11.Options", envir = .X11env)    if (d$type == "Xlib" && !missing(family)) {        fns <- X11Fonts()        if (!family %in% names(fns))             stop("unknown family for X11(type = \"XLib\")")        d$fonts[1] <- fns[[family]]    }    type <- if (capabilities("cairo"))         switch(d$type, cairo = 1L, nbcairo = 2L, dbcairo = 3L,             0L)    else 0L    if (display == "XImage")         type <- 0L    antialias <- match(d$antialias, aa.cairo)    if (grepl("darwin", R.version$os))         check_for_XQuartz()    .External2(C_X11, d$display, d$width, d$height, d$pointsize,         d$gamma, d$colortype, d$maxcubesize, d$bg, d$canvas,         d$fonts, NA_integer_, d$xpos, d$ypos, d$title, type,         antialias, d$family)    invisible()})(): a forked child should not open a graphics device>

**Comment by pedrostrusso** [comment] 2018-04-03 18:08
This can be avoided using plot=FALSE in the CEMiTool function. This is due to an unfortunate behavior caused by the ggplot2::ggplotGrob functions inside the plot_sample_tree function, which opens up a graphics device. This seems to be related to this issue: https://github.com/tidyverse/ggplot2/issues/1042 

As a workaround, if wanting to save all plots except the sample tree plot, one could use the save_plots function and individually save each of the other plots (or loop over with apply, etc).

Closing this topic for now, hoping the aforementioned issue eventually gets solved.

**Closed by pedrostrusso** 2018-04-03 18:08 UTC
